### ISSUE TITLE
Keep in front in full screen

### ISSUE THREAD

**Issue by Aerron** [jellybeansoup/macos-netflix#14]
Is it possible for the window to keep in front even if I move to another full screen?
Suppose when I swap to chrome full screen the window still remains on desktop 1.

**Comment by 0n1cOn3** [comment]
When you make a right click on the second desktop, you can set the application to the current set desktop.

**Comment by jellybeansoup** [comment]
True PiP-style behaviour is tricky (particularly the ability to float in front of fullscreen apps and stay in position when changing spaces part), but is something I've been (very slowly) exploring in relation to #6.
