### ISSUE TITLE
Can I download shows ? 

### ISSUE THREAD

**Issue by SkaarFacee** [jellybeansoup/macos-netflix#25]
One major drawback of the online Netflix app on mac is that there is no download option. Is such a feature available if not, can such a thing be implemented ?

**Comment by jellybeansoup** [comment]
Given that this app is really just designed as a lightweight wrapper around the Netflix web app, I can safely say that the feature doesn't exist, as Netflix themselves haven't implemented it. It's also worth noting that even if one were to download shows, the app itself doesn't really work when offline, so you wouldn't be able to play the shows without an internet connection in the first place.

The answer to the second part of this question is… complex. The answer is likely "yes"; if you wanted to spend time reverse-engineering the feature, you very likely could, and I don't doubt that there are those who have. However, there's also a legal aspect to this kind of thing, and I'm not sure Netflix would look kindly upon a random third-party making it possible to download shows onto a platform that could then enable sharing the content with people who don't have an account (likely part of the reason they haven't tackled it themselves).

So with regards to _this_ project: no, and no. It's not included, and I'm not going to build it. I have no intention of facing Netflix in court over a piracy charge 😬

**Comment by SkaarFacee** [comment]
Okay, that makes total sense. Thanks for the reply. I hope Netflix makes the feature available soon 😄
