### ISSUE TITLE
Maximizing Window with `Snap to Corners` Option On Causes Issues

### ISSUE THREAD

**Issue by ToniWonKanobi** [jellybeansoup/macos-netflix#4]
Sort of this crazy jittery thing and then just beach balling.

**Comment by jellybeansoup** [comment]
Yeah, I actually noticed this myself 😂

I'll actually be fixing this as part of fixing/enabling actual full screen mode, so I've created an issue for that (#5) and I'll close this one.

**Comment by ToniWonKanobi** [comment]
🚀
