### ISSUE TITLE
Minimum window size too big

### ISSUE THREAD

**Issue by MaxHasADHD** [jellybeansoup/macos-netflix#7]
Hey! Great app you have here. I'd love to make the window even smaller. On a 15" MacBookPro, theres just not enough screen space. Probably matching what PIP's minimum size would be great.

**Comment by jellybeansoup** [comment]
Totally possible. The size I chose was completely arbitrary based on what it felt like to actually browse the catalog, but there's no reason it couldn't be smaller. I'll match it to the macOS PiP window size.

While I think of it, I also need to constrain the maximum size when in "Snap to Corners" mode, as you can still cause the wiggly beachball of death by trying to resize larger than the snap area. Oops.

**Comment by drbenru** [comment]
Can you please make it half that (320x180).  My wife plays World of Warcraft while watching Netflix and she makes the window really small.  She watches murder mysteries (Midsomer Murders) while playing so she mostly listens and the image being small is not a problem.

**Comment by jellybeansoup** [comment]
@drbenru macOS's built-in PiP window can get pretty small, i've measured it at 180x102. i'm going to match that, so it should take care of your wife's concerns 😊

**Comment by jellybeansoup** [comment]
This issue should be resolved as of [v1.0.2](https://github.com/jellybeansoup/macos-netflix/releases/tag/v1.0.2), which is now officially released.
