### ISSUE TITLE
Display Error

### ISSUE THREAD

**Issue by n6ac** [jellybeansoup/macos-netflix#9]
Under Sierra on McMini ...
controlling by screensharing to another Mini also on Sierra

Whoops, ...
Display Error
There appears to be a display problem. Please ensure your monitor is HDCP compliant and is not mirrored using AirPlay
Error Code: S7363-1260-48444350

![screenshot 2018-10-21 at 3 40 56 pm](https://user-images.githubusercontent.com/6811107/47273431-0e0f1b00-d549-11e8-83e0-b0983c99b906.jpg)

**Comment by jellybeansoup** [comment]
This is related to Netflix's DRM, and not something I have any control over.

**Comment by n6ac** [comment]
OK, thanks ...
